// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMc3z9EKPLeA62ut5KSiD5rrkmkaLSqLg',
    appId: '1:454482395196:android:d285fd4f8c65b7396b8339',
    messagingSenderId: '454482395196',
    projectId: 'ecommerce-ffdbe',
    storageBucket: 'ecommerce-ffdbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiJTCSX281Wx5UWx4yQZegcaiNT0DwkTM',
    appId: '1:454482395196:ios:4b5b2886fad9eae36b8339',
    messagingSenderId: '454482395196',
    projectId: 'ecommerce-ffdbe',
    storageBucket: 'ecommerce-ffdbe.appspot.com',
    androidClientId: '454482395196-0tgf5ecvp1alhu5pjcv3m4d6lkqd1hgg.apps.googleusercontent.com',
    iosClientId: '454482395196-ohjf2nervf1j0jakt0u42gbcf2t0porq.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservationFarm',
  );
}
